### ISSUE TITLE
vue setup with latest yo kittn version V.3.83.4

### ISSUE THREAD

**Issue by manniR** [kittn/generator-kittn#31]
i've setup a project with yo kittn and vue  (runtime only) - everything works great, i use twig and scss 

commands i have run after yo kittn:
npm run init
npm run develop

no errors
twig and scss working but not vue - no output in div #app

default vue setup with app.js and app.vue is as its coming out from the yo kittn generator

what am i missing?

**Comment by gisu** [comment]
I do not quite understand why this is not with you. Just tested with Vue and Twig. Changes to the Vue files (with `npm run dev`) are injected into the page via Webpack HMR.

Now is the question which URL you use to display the page. If it is not `localhost: 3000`, you will not see any changes. Because the webpack in the `dev` task contains all changes in the memory and injected into the page via HMR.

**Comment by CinKon** [comment]
Version 3.x is out of maintainance.
Please Upgrade to v4!
